services:
  syncthing:
    image: lscr.io/linuxserver/syncthing
    container_name: syncthing
    restart: unless-stopped
    networks:
      frontend:
      backend:
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - HOME=/config
    volumes:
      - ${MOUNT_ROOT}/nadinedesktop:/data1/nadinedesktop:rw
      - ${MOUNT_ROOT}/appdata/syncthing:/config:rw
      - ${MOUNT_ROOT}:${MOUNT_ROOT}/:rw
    ports:
      - "8384:8384"
      - "21027:21027/udp"
      - "22000:22000/tcp"
      - "22000:22000/udp"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.syncthing.entrypoints=websecure"
      - "traefik.http.routers.syncthing.tls=true"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  frontend:
    external: true
  backend:
    external: true